# Generated by Django 3.2 on 2022-03-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_login', '0002_auto_20220321_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
