# Generated by Django 3.2 on 2022-03-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_login', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='code',
            new_name='invite_code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='code_for_send',
            new_name='private_code',
        ),
    ]
